on:
  push:
    branches:
      - main

env:
  AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  DOTNET_BUILD_DEPENDENCY_VERSION: '3.1.x'
  DOTNET_VERSION: '5.0.x'
  PROJECT_FILE: azure-func-dotnet-play.csproj
  OUTPUT_DIRECTORY: output

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Dev Deploy'
        id: dev-cd
        uses: ./.github/workflows/cd-template
        with:
          azure_functionapp_package_path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          bicep_manifest_file: ./deploy/resources/dev.bicep
          dotnet_build_dependency_version: ${{ env.DOTNET_BUILD_DEPENDENCY_VERSION }}
          dotnet_version: ${{ env.DOTENET_VERSION }}
          output_directory: ${{ env.OUTPUT_DIRECTORY }}
          project_file: ${{ env.PROJECT_FILE }}
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          azure_function_pub_prof: ${{ secrets.AZURE_FUNCTION_PUB_PROF }}
          azure_functionapp_name: fun-spacekattdev
          azure_resource_group: ${{ secrets.AZURE_RG }}
          azure_subscription: ${{ secrets.AZURE_SUBSCRIPTION }}