on:
  push:
    branches:
      - main

env:
  AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
  AZURE_RG: ${{ secrets.AZURE_RG }}

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: spacekatt/azure-func-dotnet-play/.github/workflows/cd-template.yml@main
        with:
          bicep_manifest_file: ./deploy/resources/dev.bicep
          azure_functionapp_name: fun-spacekattdev
          azure_subscription: ${{ env.AZURE_SUBSCRIPTION }}
          azure_resource_group: ${{ env.AZURE_RG }}