on:
  push:
    branches:
      - main

jobs:
  call-workflow-passing-data:
    uses: spacekatt/azure-func-dotnet-play/.github/workflows/cd-template.yml
    with:
      bicep_manifest_file: ./deploy/resources/dev.bicep
      azure_functionapp_name: fun-spacekattdev
      azure_subscription: '${{ secrets.AZURE_SUBSCRIPTION }}'
      azure_resource_group: '${{ secrets.AZURE_RG }}'