on: [push]

env:
  AZURE_FUNCTIONAPP_NAME: fun-spacekattfunc
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '5.0.x'

name: Azure Bicep Deploy and Publish
jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy bicep template file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./deploy/resources/main.bicep
        failOnStdErr: false

  build-publish:
    runs-on: ubuntu-latest
    steps:
    - name: 'Setup DotNet ${{ env.DOTNET_VERSION }} Env'
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      shell: bash
      run: dotnet restore

    - name: Build project
      shell: bash
      run: dotnet build --configuration Release --no-restore

    - name: 'Publish Azure Function'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTION_APP_NAME }}
        package: '$${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        publish-profile: $${{ env.AZURE_FUNCTION_PUB_PROF }}