on: [push]

env:
  AZURE_FUNCTIONAPP_NAME: fun-spacekattfunc
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '5.0'

name: Azure Bicep Deploy and Publish
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./deploy/resources/main.bicep
        failOnStdErr: false

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Env
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Build project'
      shell: bash
      run: |
        pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release
        popd

    - name: 'Publish Azure Function'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTION_APP_NAME }}
        package: '$${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        publish-profile: $${{ env.AZURE_FUNCTION_PUB_PROF }}